# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4d9f2b139ac968be2a70d5eb2c78458431d313886d1bc561ea926c8608e3cbc6223ae8f78032c01ff24b18693f02036cba148e315e4fee41a9cd4980f4e407b

test:
  secret_key_base: 61cc95c20e13b0a63fafe570d9aca6d2770863c301c3de90d2c021c92ac8b51a31df5932cd71dd9fdfae04a1d7d940661b9786662efb4dfe9db242c977dadb84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
